# Generated by Django 5.0.4 on 2024-04-25 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0002_transactiontype_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='threshold',
            name='type',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='category',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='ThresholdType',
        ),
        migrations.DeleteModel(
            name='TransactionCategory',
        ),
        migrations.DeleteModel(
            name='TransactionType',
        ),
    ]
