# Generated by Django 5.0.4 on 2024-04-25 02:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0003_alter_threshold_type_alter_transaction_category_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alert',
            old_name='name',
            new_name='message',
        ),
    ]
