# Generated by Django 5.0.4 on 2024-04-25 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0004_rename_name_alert_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alert',
            old_name='Threshold',
            new_name='threshold',
        ),
        migrations.AlterField(
            model_name='alert',
            name='message',
            field=models.TextField(),
        ),
    ]
